config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
    resources :users,only:[:show,:edit,:update] do
      resource :cart, only:[:show]
      resource :order, only:[:create,:show]  
      get :exhibitor, on: :member
  end
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
	resources :items do
		resource :cart, only:[:create,:update,:destroy]
	end
  get '/category/:area' => 'categories#category',as: :category
	root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :personal
  has_many :orders
  has_many :items 
  has_many :carts
  accepts_nested_attributes_for :personal
  accepts_nested_attributes_for :orders
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name , :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
 end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user
	before_action :authenticate_user!
	before_action :correct_user
	def show
		add_breadcrumb @user.name
	end
	def exhibitor
		@user = User.find(params[:id])
		@items = @user.items.page(params[:page]).per(15).includes(:carts,:thumbnails)
	end
	def edit
		@personal = Personal.find_by(user_id: @user.id)
	end
	def update
		@personal = Personal.find_by(user_id: @user.id)
		if @personal.update(personal_params)
			redirect_to items_path
		else
			render :edit
		end
	end
	private
	def set_user
		@user = User.find(params[:id])
	end
	def correct_user
		user = User.find(params[:id])
		if current_user.id != user.id
			redirect_to items_path
		end
	end
	private
	def personal_params
		params.require(:personal).permit(:email,:tel,:state,:city,:address,:user_id)
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def user_item_total_fee user
		user.carts.map {|f| 
			if f.is_purchase == true
				f.item.price*f.quantity
			else
				nil.to_i
			end
		}.sum
	end
	def buyer user_id
  		User.find(user_id)
	end
end

app/views/users/edit.html.erb
<div class="container">
	<%= form_for(@personal, url: user_path) do |f| %>
			<div class="form-group">
			<%= f.collection_select :state, JpPrefecture::Prefecture.all, :code, :name %>
			<%= f.text_field :city, placeholder: '市区町村',class: 'form-control' %>
			<%= f.text_field :address, placeholder: '丁目、番地',class: 'form-control' %>
			<%= f.text_field :tel, placeholder: '電話番号',class: 'form-control' %>
			</div>
		<%= f.submit '変更'%>
	<% end %>
</div>

app/views/users/exhibitor.html.erb

<div class="container">
	<h1><%= @user.name %></h1>
	<div class="col-sm-6">
	<% @items.each do |item| %>
	<div class="col-sm-6">
		<ul class="media-list">
		<% unless item.thumbnails.empty? %>
		<% item.thumbnails.each_with_index do |thumbnail,i| %>
			<li class="media"><%= image_tag thumbnail.image.url,class: 'thumbnail media-left' %></li>
			<% break if i==0 %>
		<% end %>
		<% else %>
			<li class="alt">画像が<br>ありません</li>
		<% end %>
		<div class="media-body">
		<li class="media-header"><%= item.name %></li>
		<li><%= item.price %>円</li>
		<li><%= item.description %></li>
		</div>
			<li><%= link_to '編集する',edit_item_path(item) %></li>
			<li><%= link_to '削除する', item_path(item), method: :delete %>
		</ul>
	</div>
	<% end %>
	</div>
	<div class="col-sm-6">
		販売履歴
		<% @items.each do |item| %>
			<% item.carts.each do |cart| %>
			<div>
				<%= sold_item(cart.item_id).name %>
				<%= cart.quantity %>個
				<%= cart.quantity*sold_item(cart.item_id).price %>円
				<%= buyer(cart.user_id).name%>さん
				<%= cart.order.order_date %>
			</div>
			<% end %>
		<% end %>
	</div>
</div>
<div class="page"><%= paginate @items %></div>

app/views/users/show.html.erb
<div class="container">
	<div class="jumbotron">
		<h1> <%= @user.name %></h1>
		<% unless @user.personal.nil? %>
	<ul class="list-group">
	<li class="list-group-item"><%= @user.email %></li>
	<li class="list-group-item"><%= @user.personal.prefecture.name %></li>
	<li class="list-group-item"><%= @user.personal.city %></li>
	<li class="list-group-item"><%= @user.personal.address %></li>
	<li class="list-group-item"><%= @user.personal.tel %></li>
	</ul>
	<%= link_to 'プロフィール変更', edit_user_path(current_user),class: "btn btn-primary"%>
	<% else %>
	<li class='list-group-item'>まだ購入者情報は登録されていません</li>
	<% end %>
</div>
</div>