config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
    resources :users,only:[:show,:edit,:update] do
      resource :cart, only:[:show]
      resource :order, only:[:create,:show]  
      get :exhibitor, on: :member
  end
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
	resources :items do
		resource :cart, only:[:create,:update,:destroy]
	end
  get '/category/:area' => 'categories#category',as: :category
	root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	default_scope -> {order(created_at: :desc)}
	belongs_to :item,optional: true
	belongs_to :user
	belongs_to :order,optional: true
	validates :item_id, presence: true
	validates :is_purchase, inclusion:{in:[true,false]}
	validates :quantity, numericality:{
							only_integer:true,
							greater_than: 0,
	}
	validates :order_id, :numericality => true, :allow_blank => true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
		before_action :set_item, only:[:create,:update,:destroy]
		before_action :authenticate_user!
	def create
		@cart = Cart.new(cart_params)
		@cart.item_id = @item.id
		@cart.user_id = current_user.id
		unless item_pick == false
		 	if @cart.save
		 		redirect_to items_path
		 	else
		 		redirect_to item_path(@item)
		 	end
		 else
		 	redirect_to items_path
		end
	end
	 def show
	 	@cart = Cart.where(user_id: current_user.id)
	 	unless current_user.personal.present?
	 		@personal = Personal.new
	 	else
	 		@personal = Personal.find_by(user_id: current_user)
	 	end
	 end
	def update
		@cart = Cart.find_by(item_id: @item)
		item_back
		@cart.update(cart_params)
		item_pick
		redirect_to items_path
	end
	def destroy
		@cart = current_user.carts.find_by(item_id: params[:item_id])
		item_back
		@cart.destroy
		redirect_to user_cart_path(current_user.id)
	end
	private
	def set_item
		@item = Item.find(params[:item_id])
	end
	def cart_params
		params.require(:cart).permit(:user_id,:item_id,:quantity,:is_purchase)
	end
	 def item_pick
	 	@item.backyard.update(stock: @item.backyard.stock - @cart.quantity)
	 end
	 def item_back
	 	@item.backyard.update(stock: @item.backyard.stock + @cart.quantity)
	 end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb

<h1>カート一覧</h1>
	<div class="col-sm-4">
		<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %>
		</div>
		<% end %>
		<ul class="media-list">
		<% @cart.each do |cart| %>
			<% if cart.is_purchase == true %>			
				<% unless cart.item.thumbnails.empty? %>
					<% cart.item.thumbnails.each_with_index do |thumbnail,i| %>
						<li class="media"><%= image_tag thumbnail.image.url,class: 'thumbnail media-left' %></li>
					<% break if i==0 %>
					<% end %>
				<% else %>
					<li class="alt">画像が<br>ありません</li>
				<% end %>
				<div class="media-body">
					<li class="media-header"><%= cart.item.name %></li>
					<li><%= cart.quantity %>個　カートにはいっています</li>
					<li><%= cart.item.price*cart.quantity %>円</li>
					<li><%= cart.item.description %></li>
					<li><%= link_to 'カートから出す', item_cart_path(cart.item),method: :delete %></li>
				</div>
			<% end %>
		<% end %>
		<li>合計<%= user_item_total_fee current_user %>円</li>
		</ul>
	</div>
<h2>購入する</h2>
<div class='col-sm-4'>
<% unless current_user.personal.present? %>
	<%= form_for(@personal, url: user_order_path(current_user)) do |f| %>
			<div class="form-group">
			<%= f.collection_select :state, JpPrefecture::Prefecture.all, :code, :name %>
			<%= f.text_field :city, placeholder: '市区町村',class: 'form-control' %>
			<%= f.text_field :address, placeholder: '丁目、番地',class: 'form-control' %>
			<%= f.text_field :tel, placeholder: 'TEL:〇〇〇ー〇〇〇〇ー〇〇〇〇(間にハイフンを入れてください）',class: 'form-control' %>
			</div>
		<%= f.submit '購入' %>
	<% end %>
<% else %>
<ul class="list-group">
	<li class="list-group-item"><%= current_user.email %></li>
	<li class="list-group-item"><%= @personal.prefecture.name %></li>
	<li class="list-group-item"><%= @personal.city %></li>
	<li class="list-group-item"><%= @personal.address %></li>
	<li class="list-group-item"><%= @personal.tel %></li>
	</ul>
	<%= link_to '購入者情報を変更する', user_path(current_user) %>|
	<%= link_to '購入する', user_order_path(current_user),method: :post%>
<% end %>
</div>
<% if @personal.errors.any? %>
  <div id="error_explanation">
    <h2><%= @personal.errors.count %>件のエラーがあります。</h2>
 
    <ul>
    <% @personal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>