config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
    resources :users,only:[:show,:edit,:update] do
      resource :cart, only:[:show]
      resource :order, only:[:create,:show]  
      get :exhibitor, on: :member
  end
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
	resources :items do
		resource :cart, only:[:create,:update,:destroy]
	end
  get '/category/:area' => 'categories#category',as: :category
	root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="page-header">
<% if user_signed_in? %>
		<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>|<%= link_to 'カートを確認する', user_cart_path(current_user) %>|
		<%= link_to 'マイページ', user_path(current_user) %>|
		<%= link_to '購入履歴', user_order_path(current_user) %>
	<% if current_user.exhibitor == true %>
		（出品者向け）
		<%= link_to '出品',new_item_path %>|
		<%= link_to '出品した商品一覧', exhibitor_user_path(current_user) %>|
	<% end %>
<% else %>
	<%= link_to '新規会員登録', new_user_registration_path %>|
	<%= link_to 'ログイン', new_user_session_path %>|
<% end %>

<div class='navbar navbar-default'>
	<div class="collapse navbar-collapse" id="navbarEexample">
			<ul class="nav navbar-nav">
				<li><%= link_to 'フランス',category_path(10)%></li>
				<li><%= link_to 'イタリア',category_path(20)%></li>
				<li><%= link_to 'スペイン',category_path(30)%></li>
				<li><%= link_to 'ドイツ',category_path(40)%></li>
				<li><%= link_to 'アメリカ',category_path(50)%></li>
				<li><%= link_to '日本',category_path(60)%></li>
				<li><%= link_to 'オーストラリア',category_path(70)%></li>
				<li><%= link_to 'ニュージーランド',category_path(80)%></li>
			</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task56</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render_breadcrumbs separator: ' > ' %>
    <%= yield %>
  </body>
</html>